sudo: required
services:
    - docker
after_success:
    - docker build -t tejozarkar/spring-server .

    # Login to docker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    #Push images to docker hub
    - docker push tejozarkar/spring-server