version: "3"

services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
 
  server:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
